# Generated by Django 4.2.7 on 2023-12-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('visits', models.IntegerField(default=1)),
            ],
        ),
    ]
